# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20160427_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundCondition',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offer.Condition')),
                ('conjunction', models.CharField(choices=[(b'AND', 'Logical AND'), (b'OR', 'Logical OR')], default=b'AND', max_length=10, verbose_name='Subcondition conjunction type')),
            ],
            options={
                'verbose_name': 'Compound condition',
                'verbose_name_plural': 'Compound conditions',
            },
            bases=('offer.condition',),
        ),
        migrations.AlterField(
            model_name='condition',
            name='type',
            field=models.CharField(blank=True, choices=[(b'Count', 'Depends on number of items in basket that are in condition range'), (b'Value', 'Depends on value of items in basket that are in condition range'), (b'Coverage', 'Needs to contain a set number of DISTINCT items from the condition range'), (b'Compound', 'Aggregates multiple sub-conditions together')], max_length=128, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='compoundcondition',
            name='subconditions',
            field=models.ManyToManyField(related_name='parent_condition', to='offer.Condition'),
        ),
    ]
